### ISSUE TITLE
Playmat

### ISSUE THREAD

**Issue by nationmorath** [nationmorath/DateBuilder#1]
- [x] Pile objects #2 (link to Pile Task) 
- [x] MainDeck sprite object
- [x] Discard sprite object (with quantity)
- [x] Deck sprite object (with quantity)
- [x] Scrollable lists (for hand and played)
- [x] Info HUD (Love, Venture, Turns remaining, End Turn button)
- [ ] Exit button (concede the game)
- [x] Character sprite
- [x] Character Dialog Box

**Comment by Caydo** [comment]
Lists can be scrolled with dragging. @nationmorath - I can take a look at scroll buttons later on but from what I've looked at there's no clear way to get them going in ugui currently. I'll keep looking here and there but for now I'll focus on other stuff.

**Comment by Caydo** [comment]
Scroll buttons are in and work. It just took some googling and working at it.

**Comment by Caydo** [comment]
Closing this out, the exit button is handled on its own by another task.
