### ISSUE TITLE
Add UpgradeFileName property to Cards.json file

### ISSUE THREAD

**Issue by Caydo** [nationmorath/DateBuilder#20]
For cards like Practice Makes Perfect cards need to know what their upgrade is going to be. I could pro programmatically add this but that's seems like a big-ish tech hurdle when we can just add the data to the json file.

The filename should have the same format as the regular FileName property e.g. L_R_NoDistractions. I already went in and added placeholders for all of them but I'm guessing that'll get blown away by real data.

**Comment by nationmorath** [comment]
Ignore this task! Instead, cards like that should look at the cards on the board, and pick the appropriate one of the right type and level (ignore trait) and buy the top of that pile.

**Comment by Caydo** [comment]
Closing out in favor of https://github.com/nationmorath/DateBuilder/issues/23
