### ISSUE TITLE
Change Level in Cards.Json from "Level 1", "Level 2", etc. to just "1", "2", etc.

### ISSUE THREAD

**Issue by Caydo** [nationmorath/DateBuilder#25]
To have levels be actual ints in-game the string passed in to parse for JSON needs to be an int e.g. "1" instead of "Level 1" for the "Level" attributes.

**Comment by Caydo** [comment]
I added this to the current JSON so that the game'll work but it'll be blown away next time it's deleted.

**Comment by nationmorath** [comment]
Updated Card_File.xlsx and built a new JSON.
