### ISSUE TITLE
Hook up Date Responses to LovePlayedThisTurn

### ISSUE THREAD

**Issue by nationmorath** [nationmorath/DateBuilder#28]
At the end of the turn, before LovePlayedThisTurn resets, pause and have the Date say a random response from the appropriate type (Amazed, Happy, Surprised, etc) from Characters.json

Initial placeholder values for LovePlayed threshholds:
0-2 Love: ResponseSad
3-9 Love: ResponseHappy
10-15 Love: ResponseAmazed
16+ Love: ResponseSurprised

**Comment by Caydo** [comment]
Adding a note that this should likely happen inside PlayerData's EndTurn()

**Comment by Caydo** [comment]
This is hooked up but we only use the first response in the list. Do we want one of the 4 phrases to be randomly selected? I assume yes. I'll just need to throw something in real quick to compile the phrases into a list, randomly select from the list, then use that.

**Comment by Caydo** [comment]
Done. This is set up to choose from however many responses are in the list of that type then change the text to that. Currently it's set up for add just the four responses. If we want more I'll need to change how the list is set up but otherwise things should be good.
