### ISSUE TITLE
Hang - possibly due to empty main deck?

### ISSUE THREAD

**Issue by nationmorath** [nationmorath/DateBuilder#33]
With 5 turns left, after a fair number of extra drains, the game hung with one spot still unfilled.
This is the error:
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[Card].get_Item (Int32 index) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
RefillDrainCards.DoAction () (at Assets/code/gameactions/RefillDrainCards.cs:20)
GameAction.RunAction () (at Assets/code/gameactions/GameAction.cs:41)
CardCoordinator+<turnCardDraw>c__Iterator7.MoveNext () (at Assets/code/data/CardCoordinator.cs:62)

**Comment by nationmorath** [comment]
If it is due to the deck being empty, the desired function in that case is for the game to continue without refills. The player can try to win without new MainDeck buys until their turns run out.

**Comment by Caydo** [comment]
Fixed.
