### ISSUE TITLE
Hook up date Trait sprites instead of Text in DateTraitRenderer

### ISSUE THREAD

**Issue by nationmorath** [nationmorath/DateBuilder#43]
I added sprites (Resources/Art/UI/Talent, etc) for each trait. I want to display the appropriate sprite for DateAvatar>Trait prefab, but I couldn't figure out how to set the image and pick it based on DateTrait.

**Comment by Caydo** [comment]
Implemented. The renderer needed to refer to the Image component instead of Text and the sprites needed to be wired up so they could be set.
